#!/bin/bash

set -e

#!/bin/bash

set -e

ROOT_DIR=../../../..
ISO=$ROOT_DIR/alter.iso
CONFIG=$ROOT_DIR/base/boot/limine.conf

mkdir -p iso_root/boot/

# Copy the kernel to the ISO root
cp ../../../alter.sys iso_root/boot

# Copy boot files
cp $CONFIG limine/limine-bios.sys \
    limine/limine-bios-cd.bin \
    limine/limine-uefi-cd.bin \
    iso_root/

# Generate the ISO
xorriso -as mkisofs -b limine-bios-cd.bin -no-emul-boot -boot-load-size 4 \
        -boot-info-table --efi-boot limine-uefi-cd.bin -efi-boot-part \
		--efi-boot-image --protective-msdos-label iso_root/ -o $ISO 1>/dev/null

limine/limine bios-install $ISO 1>/dev/null
rm -rf iso_root
